#!/usr/bin/env bash
# =============================================================================
# generate-ci.sh — write the server-side gate ladder for THIS project:
#   Angular (lint → build → unit tests) · .NET (build → tests incl. SQL Server
#   via Testcontainers) · Playwright UI journeys · test-guard (strict) · dependency audit
#
#   bash scripts/generate-ci.sh [--force] [--github | --azure] [--no-cd]
#
# Writes two pipelines for the git host (scripts/git-host.sh):
#   CI — the gate ladder on every PR
#        github → .github/workflows/devpilot-ci.yml · azure → azure-pipelines.yml
#        (made required by: bash scripts/protect-branches.sh)
#   CD — build ONCE, promote the same artifact DEV → SIT → UAT → PRD
#        github → .github/workflows/devpilot-cd.yml · azure → azure-pipelines-cd.yml
#        develop → DEV · release/* → SIT → UAT (approval) → PRD (approval)
#        hotfix/* → SIT → PRD (approval) · manual run on a tag → redeploy/rollback one env
#        (environments + approvals: bash scripts/setup-environments.sh)
# =============================================================================
set -uo pipefail
DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$ROOT" || exit 1
# shellcheck source=devpilot-lib.sh
. "$DIR/devpilot-lib.sh"

FORCE=0; HOST=""; CD=1
for a in "$@"; do
  case "$a" in --force) FORCE=1 ;; --github) HOST=github ;; --azure) HOST=azure ;; --no-cd) CD=0 ;; esac
done
[ -z "$HOST" ] && HOST=$(bash "$DIR/git-host.sh")
[ "$HOST" = "azure" ] || HOST="github"

if [ "$HOST" = "azure" ]; then OUT="azure-pipelines.yml"; OUT_CD="azure-pipelines-cd.yml"
else OUT=".github/workflows/devpilot-ci.yml"; OUT_CD=".github/workflows/devpilot-cd.yml"; fi

BASE=$(dp_cfg base_branch); BASE="${BASE:-develop}"
FE=$(dp_cfg stack frontend); FE="${FE:-none}"
BE=$(dp_cfg stack backend);  BE="${BE:-none}"

# Where the Angular workspace lives (repo root, or e.g. src/web, ClientApp).
NG_DIR=$(find . -name angular.json -not -path '*/node_modules/*' 2>/dev/null | head -1)
[ -n "$NG_DIR" ] && NG_DIR=$(dirname "$NG_DIR" | sed 's#^\./##')
[ -z "$NG_DIR" ] && [ -f package.json ] && NG_DIR="."
[ "$FE" = "none" ] && NG_DIR=""
[ "$FE" != "none" ] && [ -z "$NG_DIR" ] && NG_DIR="."
HAS_E2E=0
find . -maxdepth 4 -name 'playwright.config.*' -not -path '*/node_modules/*' 2>/dev/null | grep -q . && HAS_E2E=1
DOTNET=0; [ "$BE" = "dotnet" ] && DOTNET=1

# The deployable ASP.NET Core project (Sdk.Web, not a test project) and EF migrations.
API_PROJ=""
if [ "$DOTNET" = 1 ]; then
  API_PROJ=$(find . -maxdepth 5 -name '*.csproj' -not -path '*/bin/*' -not -path '*/obj/*' 2>/dev/null \
    | grep -viE 'test' | while read -r f; do grep -q 'Microsoft.NET.Sdk.Web' "$f" && echo "${f#./}"; done | head -1)
fi
# Toolchain versions FROM THE PROJECT (never assume the newest):
#   .NET SDK  global.json sdk.version → else the API's <TargetFramework> (net8.0 → 8.0.x) → else 10.0.x
#   Node      .nvmrc / .node-version → else package.json engines.node → else 22
#   dotnet-ef the project's EF Core package version (tool and runtime must match)
DOTNET_SDK="10.0.x"
if [ -f global.json ] && command -v jq >/dev/null 2>&1; then
  V=$(jq -r '.sdk.version // empty' global.json 2>/dev/null); [ -n "$V" ] && DOTNET_SDK="$(echo "$V" | cut -d. -f1-2).x"
elif [ "$DOTNET" = 1 ]; then
  TFM=$(grep -rhoE '<TargetFramework>net[0-9]+\.[0-9]+' --include='*.csproj' . 2>/dev/null | grep -v '/bin/\|/obj/' | head -1 | sed 's/.*net//')
  [ -n "$TFM" ] && DOTNET_SDK="$TFM.x"
fi
NODE_VER="22"
for F in "${NG_DIR:-.}/.nvmrc" "${NG_DIR:-.}/.node-version" .nvmrc .node-version; do
  [ -f "$F" ] && { NODE_VER=$(head -1 "$F" | tr -d 'v[:space:]' | cut -d. -f1); break; }
done
if [ "$NODE_VER" = "22" ] && [ -n "$NG_DIR" ] && [ -f "$NG_DIR/package.json" ]; then
  E=$(sed -n 's/.*"node"[[:space:]]*:[[:space:]]*"[^0-9]*\([0-9][0-9]*\).*/\1/p' "$NG_DIR/package.json" | head -1); [ -n "$E" ] && NODE_VER="$E"
fi
case "$NODE_VER" in ''|*[!0-9]*) NODE_VER="22" ;; esac

# EF Core migrations may live in another project (e.g. Infrastructure) than the API.
HAS_MIGRATIONS=0; MIG_PROJ=""
EF_VER=$(grep -rhoE 'Include="Microsoft\.EntityFrameworkCore[A-Za-z.]*"[[:space:]]+Version="[0-9]+\.[0-9]+\.[0-9]+' --include='*.csproj' . 2>/dev/null \
  | sed -E 's/.*Version="//' | sort -t. -k1,1nr -k2,2nr -k3,3nr | head -1)
MIG_DIR=$(find . -maxdepth 6 -type d -name Migrations -not -path '*/bin/*' -not -path '*/obj/*' 2>/dev/null | head -1)
if [ -n "$MIG_DIR" ] && [ "$DOTNET" = 1 ]; then
  HAS_MIGRATIONS=1
  MIG_PROJ=$(find "$(dirname "$MIG_DIR")" -maxdepth 1 -name '*.csproj' 2>/dev/null | head -1 | sed 's#^\./##')
fi

github_yml() {
cat <<YML
# Generated by devpilot (scripts/generate-ci.sh) — the gate ladder, server-side.
# Require the "devpilot-ci" check on $BASE and main (scripts/protect-branches.sh).
name: devpilot-ci

on:
  pull_request:
    branches: ["$BASE", "main", "release/**"]
  push:
    branches: ["$BASE"]

concurrency:
  group: devpilot-ci-\${{ github.ref }}
  cancel-in-progress: true

jobs:
  devpilot-ci:
    name: devpilot-ci
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # test-guard diffs against the target branch
YML
if [ -n "$NG_DIR" ]; then cat <<YML

      - uses: actions/setup-node@v4
        with:
          node-version: $NODE_VER
          cache: npm
          cache-dependency-path: $NG_DIR/package-lock.json
      - name: npm ci (Angular)
        working-directory: $NG_DIR
        run: npm ci
      - name: lint (Angular)
        working-directory: $NG_DIR
        run: npm run lint --if-present
      - name: build (Angular)
        working-directory: $NG_DIR
        run: npm run build --if-present
      - name: unit tests (Angular · Vitest)
        run: TEST_MAX_LINES=400 bash scripts/run-tests.sh angular
YML
fi
if [ "$DOTNET" = 1 ]; then cat <<YML

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: $DOTNET_SDK
      - uses: actions/cache@v4   # NuGet packages, keyed on the project files
        with:
          path: ~/.nuget/packages
          key: nuget-\${{ runner.os }}-\${{ hashFiles('**/*.csproj', '**/packages.lock.json', '**/Directory.Packages.props') }}
          restore-keys: nuget-\${{ runner.os }}-
      - name: build (.NET)
        run: dotnet build --configuration Release
      - name: tests (.NET · xUnit + Testcontainers SQL Server)
        run: dotnet test --configuration Release --no-build --logger "trx;LogFileName=results.trx"
YML
fi
if [ "$HAS_E2E" = 1 ]; then cat <<YML

      - name: Playwright browsers
        working-directory: ${NG_DIR:-.}
        run: npx playwright install --with-deps chromium
      - name: UI journeys (Playwright + axe)
        run: TEST_MAX_LINES=400 bash scripts/run-tests.sh e2e
YML
fi
cat <<'YML'

      - name: test-guard — every changed source file has a covering test
        if: github.event_name == 'pull_request'
        run: STRICT=1 bash scripts/test-guard.sh "origin/${{ github.base_ref }}"

      - name: dependency audit — no new high/critical CVEs
        run: STRICT=1 bash scripts/audit.sh

      - name: version is ahead of the target (parallel deliveries never reuse a version)
        if: github.event_name == 'pull_request' && github.base_ref != 'main'
        run: bash scripts/version.sh verify --ref "origin/${{ github.base_ref }}"

      - name: keep logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: devpilot-logs
          path: .devpilot/logs/
          if-no-files-found: ignore
YML
}

azure_yml() {
cat <<YML
# Generated by devpilot (scripts/generate-ci.sh) — the gate ladder, server-side.
# Azure Repos: PR validation is a branch policy, not a YAML trigger — add this pipeline
# as "Build validation" on $BASE and main (scripts/protect-branches.sh prints the steps).
trigger:
  branches:
    include: ["$BASE", "main", "release/*"]
pr: none

pool:
  vmImage: ubuntu-latest

jobs:
  - job: devpilot_ci
    displayName: devpilot-ci
    timeoutInMinutes: 30
    steps:
      - checkout: self
        fetchDepth: 0
YML
if [ -n "$NG_DIR" ]; then cat <<YML

      - task: NodeTool@0
        inputs:
          versionSpec: "$NODE_VER.x"
      - script: npm ci
        workingDirectory: $NG_DIR
        displayName: npm ci (Angular)
      - script: npm run lint --if-present
        workingDirectory: $NG_DIR
        displayName: lint (Angular)
      - script: npm run build --if-present
        workingDirectory: $NG_DIR
        displayName: build (Angular)
      - script: TEST_MAX_LINES=400 bash scripts/run-tests.sh angular
        displayName: unit tests (Angular · Vitest)
YML
fi
if [ "$DOTNET" = 1 ]; then cat <<YML

      - task: UseDotNet@2
        inputs:
          packageType: sdk
          version: $DOTNET_SDK
      - script: dotnet build --configuration Release
        displayName: build (.NET)
      - script: dotnet test --configuration Release --no-build --logger "trx;LogFileName=results.trx"
        displayName: tests (.NET · xUnit + Testcontainers SQL Server)
      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          testResultsFormat: VSTest
          testResultsFiles: "**/results.trx"
YML
fi
if [ "$HAS_E2E" = 1 ]; then cat <<YML

      - script: npx playwright install --with-deps chromium
        workingDirectory: ${NG_DIR:-.}
        displayName: Playwright browsers
      - script: TEST_MAX_LINES=400 bash scripts/run-tests.sh e2e
        displayName: UI journeys (Playwright + axe)
YML
fi
cat <<'YML'

      - script: STRICT=1 bash scripts/test-guard.sh "origin/${SYSTEM_PULLREQUEST_TARGETBRANCH#refs/heads/}"
        condition: eq(variables['Build.Reason'], 'PullRequest')
        displayName: test-guard — every changed source file has a covering test
      - script: STRICT=1 bash scripts/audit.sh
        displayName: dependency audit — no new high/critical CVEs
      - script: bash scripts/version.sh verify --ref "origin/${SYSTEM_PULLREQUEST_TARGETBRANCH#refs/heads/}"
        condition: and(eq(variables['Build.Reason'], 'PullRequest'), ne(variables['System.PullRequest.TargetBranch'], 'refs/heads/main'))
        displayName: version is ahead of the target (parallel deliveries never reuse a version)
      - task: PublishPipelineArtifact@1
        condition: failed()
        inputs:
          targetPath: .devpilot/logs
          artifact: devpilot-logs
YML
}

# Build steps shared by both CD flavours: out/web (Angular dist) · out/api (dotnet
# publish) · out/db (db-package.sh: migrations.sql, rollback.sql, migrations.txt) — the one artifact promoted.
cd_build_script() {
  # One command per line: under `set -e`, a failure inside an `a && b && c` chain does NOT
  # stop the script — the build would "succeed" and ship without the frontend.
  echo 'set -euo pipefail'
  echo 'mkdir -p out'
  if [ -n "$NG_DIR" ]; then
    echo "(cd '$NG_DIR' && npm ci)"
    echo "(cd '$NG_DIR' && npx ng build --configuration production)"
    echo "mkdir -p out/web"
    echo "cp -r '$NG_DIR/dist/.' out/web/"
  fi
  if [ "$DOTNET" = 1 ]; then
    echo "dotnet publish ${API_PROJ:+'$API_PROJ' }--configuration Release --output out/api -p:Version=\"\$(bash scripts/version.sh current)\""
    if [ "$HAS_MIGRATIONS" = 1 ]; then
      if [ -f .config/dotnet-tools.json ] && grep -q dotnet-ef .config/dotnet-tools.json; then echo 'dotnet tool restore >/dev/null'
      else echo "dotnet tool update --global dotnet-ef${EF_VER:+ --version $EF_VER} >/dev/null"; fi
      echo 'export PATH="$PATH:$HOME/.dotnet/tools"'
      echo "bash scripts/db-package.sh out/db ${MIG_PROJ:+--project '$MIG_PROJ' }${API_PROJ:+--startup '$API_PROJ'}"
    fi
  fi
  echo 'bash scripts/version.sh current > out/VERSION'
}

github_cd_yml() {
cat <<YML
# Generated by devpilot (scripts/generate-ci.sh) — build once, promote the same artifact.
#   $BASE → DEV · release/* → SIT → UAT (approval) → PRD (approval) · hotfix/* → SIT → PRD (approval)
#   Run manually on a tag (e.g. v1.4.0) with an environment → redeploy / roll back that environment.
# Environments + approvals: bash scripts/setup-environments.sh
# Per environment: secret DEPLOY_HOOK (or deploy/deploy.sh from scripts/deploy-init.sh + its settings)
#                  · variables API_URL, FRONTEND_URL
name: devpilot-cd

on:
  push:
    branches: ["$BASE", "release/**", "hotfix/**"]
  workflow_dispatch:
    inputs:
      environment:
        description: "Deploy this ref (e.g. a v* tag) to one environment"
        type: choice
        options: [dev, sit, uat, prd]
        required: true

concurrency:
  group: devpilot-cd-\${{ github.ref }}
  cancel-in-progress: false   # never cancel a deployment half-way

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: \${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # tags: db-package.sh diffs migrations against the previous release
      - id: version
        run: echo "version=\$(bash scripts/version.sh current)" >> "\$GITHUB_OUTPUT"
YML
[ -n "$NG_DIR" ] && cat <<YML
      - uses: actions/setup-node@v4
        with:
          node-version: $NODE_VER
          cache: npm
          cache-dependency-path: $NG_DIR/package-lock.json
YML
[ "$DOTNET" = 1 ] && cat <<YML
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: $DOTNET_SDK
      - uses: actions/cache@v4   # NuGet packages, keyed on the project files
        with:
          path: ~/.nuget/packages
          key: nuget-\${{ runner.os }}-\${{ hashFiles('**/*.csproj', '**/packages.lock.json', '**/Directory.Packages.props') }}
          restore-keys: nuget-\${{ runner.os }}-
YML
cat <<YML
      - name: build once (web + api + db script)
        run: |
$(cd_build_script | sed 's/^/          /')
      - uses: actions/upload-artifact@v4
        with:
          name: app
          path: out/
          retention-days: 30
YML
  gh_deploy_job dev  "build" \
    "needs.build.result == 'success' && ((github.event_name == 'push' && github.ref == 'refs/heads/$BASE') || inputs.environment == 'dev')"
  gh_deploy_job sit  "build" \
    "needs.build.result == 'success' && ((github.event_name == 'push' && (startsWith(github.ref, 'refs/heads/release/') || startsWith(github.ref, 'refs/heads/hotfix/'))) || inputs.environment == 'sit')"
  gh_deploy_job uat  "[build, sit]" \
    "!cancelled() && needs.build.result == 'success' && ((github.event_name == 'push' && startsWith(github.ref, 'refs/heads/release/') && needs.sit.result == 'success') || inputs.environment == 'uat')"
  gh_deploy_job prd  "[build, sit, uat]" \
    "!cancelled() && needs.build.result == 'success' && ((github.event_name == 'push' && startsWith(github.ref, 'refs/heads/release/') && needs.uat.result == 'success') || (github.event_name == 'push' && startsWith(github.ref, 'refs/heads/hotfix/') && needs.sit.result == 'success') || inputs.environment == 'prd')"
}

# Settings the deploy templates read (scripts/deploy-init.sh) — passed to every deploy step;
# unset ones are simply empty. GitHub: environment secret or variable of that name.
DEPLOY_VARS="AZURE_CLIENT_ID AZURE_CLIENT_SECRET AZURE_TENANT_ID AZURE_SUBSCRIPTION_ID AZURE_RESOURCE_GROUP
API_APP WEB_APP SLOT SQL_SERVER SQL_DATABASE SQL_USER SQL_PASSWORD SQL_AUTH
REGISTRY REGISTRY_USER REGISTRY_PASSWORD KUBE_CONFIG KUBE_NAMESPACE
IIS_SERVER IIS_USER IIS_SSH_KEY IIS_API_PATH IIS_API_POOL IIS_WEB_PATH IIS_WEB_POOL"

gh_deploy_job() {  # gh_deploy_job <env> <needs> <condition>
  local e="$1" up; up=$(printf '%s' "$1" | tr '[:lower:]' '[:upper:]')
cat <<YML

  $e:
    needs: $2
    if: \${{ $3 }}
    runs-on: ubuntu-latest
    environment:
      name: $e
      url: \${{ vars.FRONTEND_URL }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: app
          path: out/
      - name: deploy v\${{ needs.build.outputs.version }} → $up
        run: bash scripts/deploy.sh $e out
        env:
          DEPLOY_HOOK: \${{ secrets.DEPLOY_HOOK }}
          ${up}_API_URL: \${{ vars.API_URL }}
          ${up}_FRONTEND_URL: \${{ vars.FRONTEND_URL }}
YML
  local v
  for v in $DEPLOY_VARS; do printf '          %s: ${{ secrets.%s || vars.%s }}\n' "$v" "$v" "$v"; done
}

azure_cd_yml() {
cat <<YML
# Generated by devpilot (scripts/generate-ci.sh) — build once, promote the same artifact.
#   $BASE → DEV · release/* → SIT → UAT (approval) → PRD (approval) · hotfix/* → SIT → PRD (approval)
#   Run manually on a tag with "environment" set → redeploy / roll back that one environment.
# Environments + approvals + this pipeline: bash scripts/setup-environments.sh
# Variables (pipeline or library group): DEPLOY_HOOK_<ENV> (secret), <ENV>_API_URL, <ENV>_FRONTEND_URL,
# and the deploy target's settings per stage, e.g. PRD_API_APP, PRD_SQL_SERVER (scripts/deploy-init.sh)
trigger:
  branches:
    include: ["$BASE", "release/*", "hotfix/*"]
pr: none

parameters:
  - name: environment
    displayName: Deploy only to (manual runs)
    type: string
    default: auto
    values: [auto, dev, sit, uat, prd]

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: build
        steps:
          - checkout: self
            fetchDepth: 0
            fetchTags: true
YML
[ -n "$NG_DIR" ] && cat <<YML
          - task: NodeTool@0
            inputs:
              versionSpec: "$NODE_VER.x"
YML
[ "$DOTNET" = 1 ] && cat <<YML
          - task: UseDotNet@2
            inputs:
              packageType: sdk
              version: $DOTNET_SDK
YML
cat <<YML
          - script: |
$(cd_build_script | sed 's/^/              /')
            displayName: build once (web + api + db script)
          - publish: out
            artifact: app
YML
  local AUTO="eq('\${{ parameters.environment }}', 'auto')"
  local REL="startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')"
  local HOT="startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix/')"
  local OK="in(dependencies.Build.result, 'Succeeded')"
  az_stage DEV dev "Build" \
    "and($OK, or(and($AUTO, eq(variables['Build.SourceBranch'], 'refs/heads/$BASE')), eq('\${{ parameters.environment }}', 'dev')))"
  az_stage SIT sit "Build" \
    "and($OK, or(and($AUTO, or($REL, $HOT)), eq('\${{ parameters.environment }}', 'sit')))"
  az_stage UAT uat "[Build, SIT]" \
    "and($OK, or(and($AUTO, $REL, in(dependencies.SIT.result, 'Succeeded')), eq('\${{ parameters.environment }}', 'uat')))"
  az_stage PRD prd "[Build, SIT, UAT]" \
    "and($OK, or(and($AUTO, $REL, in(dependencies.UAT.result, 'Succeeded')), and($AUTO, $HOT, in(dependencies.SIT.result, 'Succeeded')), eq('\${{ parameters.environment }}', 'prd')))"
}

az_stage() {  # az_stage <STAGE> <env> <dependsOn> <condition>
cat <<YML

  - stage: $1
    dependsOn: $3
    condition: $4
    jobs:
      - deployment: deploy_$2
        displayName: deploy → $1
        environment: $2
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - download: current
                  artifact: app
                - script: bash scripts/deploy.sh $2 "\$(Pipeline.Workspace)/app"
                  displayName: deploy + smoke test
                  env:
                    DEPLOY_HOOK: \$(DEPLOY_HOOK_$1)
                    $1_API_URL: \$($1_API_URL)
                    $1_FRONTEND_URL: \$($1_FRONTEND_URL)
YML
  local v
  for v in $DEPLOY_VARS; do printf '                    %s: $(%s_%s)\n' "$v" "$1" "$v"; done
}

# write <file> <generator> — each file honours --force independently
write() {
  if [ -f "$1" ] && [ "$FORCE" = 0 ]; then
    echo "ℹ️  $1 already exists — re-generate with: bash scripts/generate-ci.sh --force"
    return 0
  fi
  mkdir -p "$(dirname "$1")"
  "$2" > "$1"
  echo "✅ $1 written"
}

if [ "$HOST" = "azure" ]; then write "$OUT" azure_yml; else write "$OUT" github_yml; fi
if [ "$CD" = 1 ]; then
  if [ "$HOST" = "azure" ]; then write "$OUT_CD" azure_cd_yml; else write "$OUT_CD" github_cd_yml; fi
fi
echo "   toolchain: .NET SDK $DOTNET_SDK · Node $NODE_VER${EF_VER:+ · dotnet-ef $EF_VER}"
echo "   host: $HOST · angular: ${NG_DIR:-none} · api: ${API_PROJ:-${BE}} · migrations: $([ "$HAS_MIGRATIONS" = 1 ] && echo yes || echo no) · e2e: $([ "$HAS_E2E" = 1 ] && echo yes || echo no) · base: $BASE"
echo "   Next: bash scripts/protect-branches.sh (CI required) · bash scripts/setup-environments.sh (CD approvals)"
