#!/bin/bash
# Generate docs/backlog/index.md — a compact, always-loadable map of the Jira backlog.
#
# This is the "dedup brain" data source for /dp-plan. Instead of loading the whole
# backlog into context, /dp-plan reads this small index, scores a new issue against
# it (keyword + component overlap), and then reads the full spec of only the top 1-3
# candidates. Keeps token cost flat as the backlog grows.
#
# Usage: bash scripts/generate-backlog-index.sh
set -euo pipefail

# This script is Jira-specific; bypass the tracker abstraction in config sourcing.
ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
# shellcheck source=/dev/null
source "$ROOT/.devpilot/config.sh"

OUT="$ROOT/docs/backlog/index.md"
mkdir -p "$(dirname "$OUT")"

JQL="project = $JIRA_PROJECT_KEY ORDER BY created ASC"
FIELDS='["summary","issuetype","status","labels","components","parent","priority"]'

# Atlassian replaced /rest/api/3/search with /rest/api/3/search/jql (2025). Try the
# new endpoint first, fall back to the legacy one for older Jira instances.
_search() {
  local endpoint="$1"
  curl -s --request POST \
    --url "$JIRA_BASE_URL/rest/api/3/$endpoint" \
    --user "$JIRA_EMAIL:$JIRA_API_TOKEN" \
    --header "Accept: application/json" \
    --header "Content-Type: application/json" \
    --data "$(jq -n --arg jql "$JQL" --argjson fields "$FIELDS" \
      '{jql:$jql, maxResults:200, fields:$fields}')"
}

RESPONSE="$(_search "search/jql")"
if [ "$(echo "$RESPONSE" | jq -r 'has("issues")')" != "true" ]; then
  RESPONSE="$(_search "search")"
fi
if [ "$(echo "$RESPONSE" | jq -r 'has("issues")')" != "true" ]; then
  echo "❌ Jira search failed: $(echo "$RESPONSE" | jq -c '.errorMessages // .' 2>/dev/null || echo "$RESPONSE")" >&2
  exit 1
fi

GENERATED="$(date '+%Y-%m-%d %H:%M:%S')"
TOTAL="$(echo "$RESPONSE" | jq '.issues | length')"

# Build a compact one-row-per-issue table. "keywords" = labels + components, the
# cheap matching signal. parent column ties Stories/Tasks back to their Epic.
{
  echo "# Backlog Index"
  echo ""
  echo "> Generated: $GENERATED · Project: $JIRA_PROJECT_KEY · Issues: $TOTAL"
  echo "> Auto-generated by scripts/generate-backlog-index.sh — do not edit by hand."
  echo "> Used by /dp-plan as the dedup brain. Match new issues here first; read full specs only for top candidates."
  echo ""
  echo "| Key | Type | Status | Parent | Keywords | Title |"
  echo "|-----|------|--------|--------|----------|-------|"
  echo "$RESPONSE" | jq -r '
    .issues[]
    | [ .key,
        (.fields.issuetype.name // "-"),
        (.fields.status.name // "-"),
        (.fields.parent.key // "-"),
        ( ((.fields.labels // []) + ((.fields.components // []) | map(.name)))
          | unique | join(", ") | if . == "" then "-" else . end ),
        (.fields.summary // "-" | gsub("[|\n]"; " "))
      ]
    | "| " + join(" | ") + " |"
  '
} > "$OUT"

echo "✅ Backlog index written: docs/backlog/index.md ($TOTAL issues)"
