#!/usr/bin/env bash
# =============================================================================
# generate-ci.sh — write the server-side gate ladder for THIS project:
#   Angular (lint → build → unit tests) · .NET (build → tests incl. SQL Server
#   via Testcontainers) · Playwright UI journeys · test-guard (strict) · dependency audit
#
#   bash scripts/generate-ci.sh [--force] [--github | --azure]
#
# Git host (scripts/git-host.sh) picks the flavour:
#   github → .github/workflows/devpilot-ci.yml   (require the "devpilot-ci" check:
#            bash scripts/protect-branches.sh)
#   azure  → azure-pipelines.yml                 (add it as the Build validation
#            policy on develop + main: bash scripts/protect-branches.sh prints how)
# =============================================================================
set -uo pipefail
DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$ROOT" || exit 1
# shellcheck source=devpilot-lib.sh
. "$DIR/devpilot-lib.sh"

FORCE=0; HOST=""
for a in "$@"; do
  case "$a" in --force) FORCE=1 ;; --github) HOST=github ;; --azure) HOST=azure ;; esac
done
[ -z "$HOST" ] && HOST=$(bash "$DIR/git-host.sh")
[ "$HOST" = "azure" ] || HOST="github"

if [ "$HOST" = "azure" ]; then OUT="azure-pipelines.yml"; else OUT=".github/workflows/devpilot-ci.yml"; fi
if [ -f "$OUT" ] && [ "$FORCE" = 0 ]; then
  echo "ℹ️  $OUT already exists — re-generate with: bash scripts/generate-ci.sh --force"
  exit 0
fi

BASE=$(dp_cfg base_branch); BASE="${BASE:-develop}"
FE=$(dp_cfg stack frontend); FE="${FE:-none}"
BE=$(dp_cfg stack backend);  BE="${BE:-none}"

# Where the Angular workspace lives (repo root, or e.g. src/web, ClientApp).
NG_DIR=$(find . -name angular.json -not -path '*/node_modules/*' 2>/dev/null | head -1 | xargs -r dirname | sed 's#^\./##')
[ -z "$NG_DIR" ] && [ -f package.json ] && NG_DIR="."
[ "$FE" = "none" ] && NG_DIR=""
[ "$FE" != "none" ] && [ -z "$NG_DIR" ] && NG_DIR="."
HAS_E2E=0
find . -maxdepth 4 -name 'playwright.config.*' -not -path '*/node_modules/*' 2>/dev/null | grep -q . && HAS_E2E=1
DOTNET=0; [ "$BE" = "dotnet" ] && DOTNET=1

github_yml() {
cat <<YML
# Generated by devpilot (scripts/generate-ci.sh) — the gate ladder, server-side.
# Require the "devpilot-ci" check on $BASE and main (scripts/protect-branches.sh).
name: devpilot-ci

on:
  pull_request:
    branches: ["$BASE", "main", "release/**"]
  push:
    branches: ["$BASE"]

concurrency:
  group: devpilot-ci-\${{ github.ref }}
  cancel-in-progress: true

jobs:
  devpilot-ci:
    name: devpilot-ci
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # test-guard diffs against the target branch
YML
if [ -n "$NG_DIR" ]; then cat <<YML

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: $NG_DIR/package-lock.json
      - name: npm ci (Angular)
        working-directory: $NG_DIR
        run: npm ci
      - name: lint (Angular)
        working-directory: $NG_DIR
        run: npm run lint --if-present
      - name: build (Angular)
        working-directory: $NG_DIR
        run: npm run build --if-present
      - name: unit tests (Angular · Vitest)
        run: TEST_MAX_LINES=400 bash scripts/run-tests.sh angular
YML
fi
if [ "$DOTNET" = 1 ]; then cat <<'YML'

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      - name: build (.NET)
        run: dotnet build --configuration Release
      - name: tests (.NET · xUnit + Testcontainers SQL Server)
        run: dotnet test --configuration Release --no-build --logger "trx;LogFileName=results.trx"
YML
fi
if [ "$HAS_E2E" = 1 ]; then cat <<YML

      - name: Playwright browsers
        working-directory: ${NG_DIR:-.}
        run: npx playwright install --with-deps chromium
      - name: UI journeys (Playwright + axe)
        run: TEST_MAX_LINES=400 bash scripts/run-tests.sh e2e
YML
fi
cat <<'YML'

      - name: test-guard — every changed source file has a covering test
        if: github.event_name == 'pull_request'
        run: STRICT=1 bash scripts/test-guard.sh "origin/${{ github.base_ref }}"

      - name: dependency audit — no new high/critical CVEs
        run: STRICT=1 bash scripts/audit.sh

      - name: keep logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: devpilot-logs
          path: .devpilot/logs/
          if-no-files-found: ignore
YML
}

azure_yml() {
cat <<YML
# Generated by devpilot (scripts/generate-ci.sh) — the gate ladder, server-side.
# Azure Repos: PR validation is a branch policy, not a YAML trigger — add this pipeline
# as "Build validation" on $BASE and main (scripts/protect-branches.sh prints the steps).
trigger:
  branches:
    include: ["$BASE", "main", "release/*"]
pr: none

pool:
  vmImage: ubuntu-latest

jobs:
  - job: devpilot_ci
    displayName: devpilot-ci
    timeoutInMinutes: 30
    steps:
      - checkout: self
        fetchDepth: 0
YML
if [ -n "$NG_DIR" ]; then cat <<YML

      - task: NodeTool@0
        inputs:
          versionSpec: "22.x"
      - script: npm ci
        workingDirectory: $NG_DIR
        displayName: npm ci (Angular)
      - script: npm run lint --if-present
        workingDirectory: $NG_DIR
        displayName: lint (Angular)
      - script: npm run build --if-present
        workingDirectory: $NG_DIR
        displayName: build (Angular)
      - script: TEST_MAX_LINES=400 bash scripts/run-tests.sh angular
        displayName: unit tests (Angular · Vitest)
YML
fi
if [ "$DOTNET" = 1 ]; then cat <<'YML'

      - task: UseDotNet@2
        inputs:
          packageType: sdk
          version: 10.0.x
      - script: dotnet build --configuration Release
        displayName: build (.NET)
      - script: dotnet test --configuration Release --no-build --logger "trx;LogFileName=results.trx"
        displayName: tests (.NET · xUnit + Testcontainers SQL Server)
      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          testResultsFormat: VSTest
          testResultsFiles: "**/results.trx"
YML
fi
if [ "$HAS_E2E" = 1 ]; then cat <<YML

      - script: npx playwright install --with-deps chromium
        workingDirectory: ${NG_DIR:-.}
        displayName: Playwright browsers
      - script: TEST_MAX_LINES=400 bash scripts/run-tests.sh e2e
        displayName: UI journeys (Playwright + axe)
YML
fi
cat <<'YML'

      - script: STRICT=1 bash scripts/test-guard.sh "origin/${SYSTEM_PULLREQUEST_TARGETBRANCH#refs/heads/}"
        condition: eq(variables['Build.Reason'], 'PullRequest')
        displayName: test-guard — every changed source file has a covering test
      - script: STRICT=1 bash scripts/audit.sh
        displayName: dependency audit — no new high/critical CVEs
      - task: PublishPipelineArtifact@1
        condition: failed()
        inputs:
          targetPath: .devpilot/logs
          artifact: devpilot-logs
YML
}

mkdir -p "$(dirname "$OUT")"
if [ "$HOST" = "azure" ]; then azure_yml > "$OUT"; else github_yml > "$OUT"; fi

echo "✅ $OUT written (host: $HOST · angular: ${NG_DIR:-none} · backend: $BE · e2e: $([ "$HAS_E2E" = 1 ] && echo yes || echo no) · base: $BASE)"
echo "   Make it required on $BASE + main: bash scripts/protect-branches.sh"
