#!/usr/bin/env bash
# =============================================================================
# generate-ci.sh — write a stack-aware GitHub Actions workflow for THIS project
# that enforces the devpilot gate ladder server-side:
#   build → tests → test-guard (strict) → dependency audit
#
#   bash scripts/generate-ci.sh            # writes .github/workflows/devpilot-ci.yml
#   bash scripts/generate-ci.sh --force    # overwrite an existing workflow
#
# The job is named `devpilot-ci` so branch protection can require exactly that
# status check (scripts/protect-branches.sh). Stack steps come from
# project.config.md; re-run after changing the stack.
# =============================================================================
set -uo pipefail

ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$ROOT" || exit 1

OUT=".github/workflows/devpilot-ci.yml"
if [ -f "$OUT" ] && [ "${1:-}" != "--force" ]; then
  echo "ℹ️  $OUT already exists — re-generate with: bash scripts/generate-ci.sh --force"
  exit 0
fi

cfg_under() {
  grep -A 8 "^$1:" project.config.md 2>/dev/null \
    | grep -E "^[[:space:]]+$2:" | head -1 \
    | sed "s/.*$2:[[:space:]]*//; s/#.*//" | tr -d '"' | awk '{print $1}'
}

BASE=$(grep '^base_branch:' project.config.md 2>/dev/null | head -1 | sed 's/base_branch:[[:space:]]*//; s/#.*//' | tr -d '"' | awk '{print $1}')
BASE="${BASE:-develop}"
FE=$(cfg_under stack frontend);  FE="${FE:-none}"
BE=$(cfg_under stack backend);   BE="${BE:-none}"

mkdir -p .github/workflows

{
cat <<YML
# Generated by devpilot (scripts/generate-ci.sh) — the gate ladder, server-side.
# Branch protection should require the "devpilot-ci" check (scripts/protect-branches.sh).
name: devpilot-ci

on:
  pull_request:
    branches: ["$BASE", "main"]
  push:
    branches: ["$BASE"]

jobs:
  devpilot-ci:
    name: devpilot-ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # test-guard diffs against $BASE
YML

# ── Node / frontend toolchain ─────────────────────────────────────────────────
if [ "$BE" = "node" ] || { [ "$FE" != "none" ] && [ -f package.json ]; }; then
cat <<'YML'

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: install
        run: npm ci
      - name: lint
        run: npm run lint --if-present
      - name: build
        run: npm run build --if-present
      - name: test
        run: npm test --if-present -- --watch=false 2>/dev/null || npm test --if-present
YML
fi

# ── Backend toolchains ────────────────────────────────────────────────────────
case "$BE" in
  dotnet) cat <<'YML'

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - name: build (.NET)
        run: dotnet build --configuration Release
      - name: test (.NET)
        run: dotnet test --configuration Release --no-build
YML
  ;;
  python) cat <<'YML'

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: install (python)
        run: |
          [ -f requirements.txt ] && pip install -r requirements.txt || true
          [ -f pyproject.toml ] && pip install -e ".[dev]" 2>/dev/null || pip install -e . 2>/dev/null || true
          pip install pytest
      - name: test (python)
        run: pytest -q
YML
  ;;
  go) cat <<'YML'

      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: build (go)
        run: go build ./...
      - name: test (go)
        run: go test ./...
YML
  ;;
  java) cat <<'YML'

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven
      - name: verify (maven)
        run: mvn -B verify
YML
  ;;
esac

# ── devpilot gates (always) ───────────────────────────────────────────────────
cat <<YML

      - name: test-guard — every changed source file has a covering test
        if: github.event_name == 'pull_request'
        run: STRICT=1 bash scripts/test-guard.sh "origin/$BASE"

      - name: dependency audit — no new high/critical CVEs
        run: bash scripts/audit.sh
YML
} > "$OUT"

echo "✅ $OUT written (stack: frontend=$FE backend=$BE · base: $BASE)"
echo "   Require this check on $BASE: bash scripts/protect-branches.sh"
