#!/bin/bash
# Generates docs/project-index.md — a fast-scan map of the codebase.
# BA agent reads this instead of scanning every file.
# Run manually or auto-called after each BA phase.

ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
OUT="$ROOT/docs/project-index.md"
mkdir -p "$ROOT/docs"
DATE="$(date '+%Y-%m-%d %H:%M')"

# ---------------------------------------------------------------------------
# Read stack from project.config.md
# ---------------------------------------------------------------------------
CONFIG="$ROOT/project.config.md"
HAS_FRONTEND=false
HAS_BACKEND=false
HAS_DB=false

if [ -f "$CONFIG" ]; then
  grep -q 'frontend:.*true\|frontend:.*angular\|frontend:.*react\|frontend:.*vue\|frontend:.*nextjs' "$CONFIG" 2>/dev/null && HAS_FRONTEND=true
  grep -q 'backend:.*true\|backend:.*dotnet\|backend:.*node\|backend:.*python' "$CONFIG" 2>/dev/null && HAS_BACKEND=true
  grep -q 'database:.*true\|database:.*sql\|database:.*postgres\|database:.*mysql' "$CONFIG" 2>/dev/null && HAS_DB=true
fi

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
# Write a section header
section() {
  printf '\n## %s\n' "$1" >> "$OUT"
}

# Scan for files matching a pattern under $ROOT/<dir>
# Writes: "  relative/path — label" per file found
scan() {
  local dir="$1"
  local pattern="$2"
  local full_dir="$ROOT/$dir"

  [ -d "$full_dir" ] || return 0

  while IFS= read -r f; do
    [ -f "$f" ] || continue
    local rel="${f#$ROOT/}"
    # Extract a short class/function name from the file
    local decl
    decl=$(grep -m1 -oE '(class|interface|enum|function|const) [A-Za-z][A-Za-z0-9_]+' "$f" 2>/dev/null | head -1 || true)
    if [ -z "$decl" ]; then
      decl=$(basename "$f" | sed 's/\.[^.]*$//')
    fi
    printf '  %-65s — %s\n' "$rel" "$decl" >> "$OUT"
  done < <(
    find "$full_dir" \
      -name "$pattern" \
      ! -path "*/node_modules/*" \
      ! -path "*/.git/*" \
      ! -path "*/dist/*" \
      ! -path "*/.angular/*" \
      ! -path "*/obj/*" \
      ! -path "*/bin/*" \
      -type f 2>/dev/null \
    | sort
  )
  return 0
}

# ---------------------------------------------------------------------------
# Write index header
# ---------------------------------------------------------------------------
cat > "$OUT" << HEADER
# Project Index
> Auto-generated by devpilot — do not edit. Refresh: \`bash scripts/generate-project-index.sh\`
> Last updated: $DATE
>
> **BA agent instructions**: Read this file first. Find the 3-5 entries most relevant to the task.
> Read only those files. Never scan the whole codebase.

HEADER

# ── Frontend ────────────────────────────────────────────────────────────────
if $HAS_FRONTEND; then
  section "Routing / Navigation"
  scan "apps" "*.routes.ts"
  scan "apps" "app-routing.module.ts"
  scan "src"  "*.routes.ts"
  scan "src"  "app-routing.module.ts"

  section "Pages"
  scan "apps" "*.page.ts"
  scan "src"  "*.page.ts"
  scan "src/pages" "*.tsx"
  scan "app"  "page.tsx"

  section "Components"
  scan "apps" "*.component.ts"
  scan "src"  "*.component.ts"
  scan "src/components" "*.tsx"
  scan "components" "*.tsx"

  section "Services / Stores (Frontend)"
  scan "apps" "*.service.ts"
  scan "apps" "*.store.ts"
  scan "src"  "*.service.ts"
  scan "src"  "*.store.ts"
  scan "src/hooks" "*.ts"

  section "Shared Libraries"
  scan "libs" "*.ts"
  scan "libs" "*.tsx"
fi

# ── Backend ─────────────────────────────────────────────────────────────────
if $HAS_BACKEND; then
  section "API Controllers / Endpoints (.NET)"
  scan "apps" "*Controller.cs"
  scan "src"  "*Controller.cs"
  scan "apps" "*Endpoint.cs"

  section "Commands / Queries / Handlers (CQRS)"
  scan "apps" "*Command.cs"
  scan "apps" "*Query.cs"
  scan "apps" "*Handler.cs"

  section "Domain Services"
  scan "apps" "*Service.cs"
  scan "src"  "*Service.cs"

  section "Node / Python Routes"
  scan "src"  "*.routes.ts"
  scan "src"  "*.controller.ts"
  scan "api"  "routes.py"
  scan "api"  "views.py"
fi

# ── Database ─────────────────────────────────────────────────────────────────
if $HAS_DB; then
  section "Entities / Models"
  scan "apps" "*Entity.cs"
  scan "apps" "*.Model.cs"
  scan "src"  "*Entity.cs"

  section "DB Context / Repositories"
  scan "apps" "*DbContext.cs"
  scan "apps" "*Repository.cs"
  scan "src"  "*DbContext.cs"

  section "EF Core Migrations"
  while IFS= read -r f; do
    [ -f "$f" ] || continue
    rel="${f#$ROOT/}"
    printf '  %s\n' "$rel" >> "$OUT"
  done < <(find "$ROOT" -path "*/Migrations/*.cs" ! -path "*/obj/*" ! -path "*/bin/*" -type f 2>/dev/null | sort)
fi

# ── Shared DTOs ──────────────────────────────────────────────────────────────
section "Shared Models / DTOs"
scan "libs/shared-models" "*.ts"
scan "apps" "*Dto.cs"
scan "apps" "*.Request.cs"
scan "apps" "*.Response.cs"
scan "src"  "*Dto.cs"

# ── Entry Points / Config ─────────────────────────────────────────────────────
section "Entry Points / Key Config"
for f in \
  "apps/api/Program.cs" \
  "apps/api/appsettings.json" \
  "apps/mobile/src/main.ts" \
  "apps/web/src/main.ts" \
  "apps/admin/src/main.ts" \
  "src/main.ts" \
  "package.json" \
  "nx.json"; do
  [ -f "$ROOT/$f" ] && printf '  %s\n' "$f" >> "$OUT"
done

# ── Existing docs ─────────────────────────────────────────────────────────────
section "Project Docs (read for domain context)"
for f in \
  "docs/02-claude-context.md" \
  "docs/05-roadmap.md" \
  "CLAUDE.md" \
  "README.md"; do
  [ -f "$ROOT/$f" ] && printf '  %s\n' "$f" >> "$OUT"
done

# ── Summary ──────────────────────────────────────────────────────────────────
COUNT=$(grep -c '^\s\+' "$OUT" 2>/dev/null || echo 0)
echo "" >> "$OUT"
echo "---" >> "$OUT"
echo "_$COUNT files indexed_" >> "$OUT"

echo "✅ Project index written → docs/project-index.md ($COUNT entries)"
