#!/usr/bin/env bash
# =============================================================================
# generate-backlog-index.sh — docs/backlog/index.md, a compact one-row-per-item
# map of the backlog in whichever tracker is active (local | jira | azure | github).
#
# The "dedup brain" data source for /dp-plan: it reads this small index plus the
# live `tracker.sh search` result, then opens the full spec of only the top 1–3
# candidates. Keeps token cost flat as the backlog grows.
#
#   bash scripts/generate-backlog-index.sh
# =============================================================================
set -uo pipefail
DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
OUT="$ROOT/docs/backlog/index.md"
mkdir -p "$(dirname "$OUT")"

TYPE=$(bash "$DIR/tracker.sh" type)
ROWS=$(bash "$DIR/tracker.sh" list) || { echo "❌ could not list the $TYPE backlog — index left unchanged" >&2; exit 1; }
TOTAL=$(printf '%s' "$ROWS" | grep -c . || true)
OPEN=$(printf '%s\n' "$ROWS" | awk -F'\t' 'NF && $4 != "done"' | grep -c . || true)

{
  echo "# Backlog Index"
  echo ""
  echo "> Generated: $(date '+%Y-%m-%d %H:%M:%S') · Tracker: $TYPE · Items: $TOTAL ($OPEN open)"
  echo "> Auto-generated by scripts/generate-backlog-index.sh — do not edit by hand."
  echo "> /dp-plan matches new work here first; full specs are read only for the top candidates."
  echo ""
  echo "| Key | Type | Status | Parent | Title |"
  echo "|-----|------|--------|--------|-------|"
  printf '%s\n' "$ROWS" | awk -F'\t' 'NF >= 6 { gsub(/\|/, "/", $6); printf "| %s | %s | %s | %s | %s |\n", $1, $2, $3, $5, $6 }'
} > "$OUT"

echo "✅ Backlog index written: docs/backlog/index.md ($TOTAL items, $OPEN open · $TYPE)"
